services:
  app:
    build: ./app
    container_name: express_app
    ports:
      - "3000:3000"
    network_mode: "host"
    environment:
      PORT: 3000
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: psql
      DB_NAME: mydb

      
  # redis:
  #   image: redis:7
  #   container_name: redis
  #   ports:
  #     - "6378:6379"
  #   networks:
  #     - monitoring

  # db:
  #   image: postgres:15
  #   container_name: postgres_db
  #   restart: always
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   networks:
  #     - monitoring


  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    ports:
      - "9100:9100"
    network_mode: "host"

