{
 "title": "Express vs Fastify Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Average Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)"
    }
   ]
  },
  {
   "title": "Success Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_request_duration_seconds_count{status_code=~\"2..\"}[1m])) / sum by (job) (rate(http_request_duration_seconds_count[1m])) * 100"
    }
   ]
  }
 ]
}